export const ADD_DATA = "ADD_DATA"
export const DELETE_DATA = "DELETE_DATA"
export const UPDATE_DATA = "UPDATE_DATA"
export const EDIT_DATA = "EDIT_DATA"
export const CLEAR_ALL_DATA = "CLEAR_ALL_DATA"
export const MULTI_DELETE_DATA = "MULTI_DELETE_DATA"